# Generated by Django 5.2.6 on 2025-10-15 23:35

import wagtailmarkdown.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webikwa_templates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footertext',
            name='body',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, help_text='A markdown version of the body. Both this and the streamfield version body will be displayed if they have content'),
        ),
    ]
